global:
  scrape_interval: 10s # Prometheus recolectará datos cada 10 segundos

scrape_configs:
  # Trabajo 1: Monitorea el servidor usando Node Exporter
  - job_name: 'servidor'
    static_configs:
      - targets: ['node-exporter:9100']

  # Trabajo 2: Monitorea el Contenedor (La App Node.js)
  - job_name: 'aplicacion_nodejs'
    static_configs:
      - targets: ['app-node:3000']
