name: CI/CD Smart Blue-Green Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute Smart Deployment via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 35.208.11.45
          username: g2016348092
          key: ${{ secrets.SSH_KEY }}
          fingerprint: "SHA256:kLQPAj/8xxkctJmqmGIw4fXwAOy1havz1ROyzmZpTTA"
          script: |
          
            if [ -f ~/current_deploy.env ]; then
                source ~/current_deploy.env
            else
                DEPLOY_COLOR=blue
            fi
            if [ "$DEPLOY_COLOR" == "blue" ]; then
                export TARGET_COLOR="green"
                export TARGET_PORT="8081"
            else
                export TARGET_COLOR="blue"
                export TARGET_PORT="8080"
            fi
            echo "Ambiente actual: $DEPLOY_COLOR. Desplegando en: $TARGET_COLOR (Puerto $TARGET_PORT)"
            export APP_TARGET_IP="127.0.0.1"
            export APP_TARGET_PORT=$TARGET_PORT
            export DEPLOYMENT_COLOR=$TARGET_COLOR
        
            envsubst '$APP_TARGET_IP $APP_TARGET_PORT $DEPLOYMENT_COLOR' < ~/nginx.conf.template > /tmp/default.conf
            sudo mv /tmp/default.conf /etc/nginx/conf.d/default.conf

            
            if sudo nginx -t; then
                sudo systemctl reload nginx
                echo "DEPLOY_COLOR=$TARGET_COLOR" > ~/current_deploy.env
                echo "Despliegue exitoso en $TARGET_COLOR"
            else
                echo "Error en la validación de Nginx"
                exit 1
            fi
